name: Deploy to Dockerhub

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bossdocker:latest
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: janreher.azurecr.io
        username: janreher
        password: ${{ secrets.azurecr_login }}
    - name: Upload Docker Image
      run: |
        docker tag bossdocker:latest janreher.azurecr.io/boss:latest
        docker push janreher.azurecr.io/boss:latest
