name: Deploy all versions

on:
  workflow_run:
    workflows: |
      Deploy .tar.gz files
      Deploy Image -- Latest
    types:
      - completed
  workflow_dispatch:
    inputs:
      deploy-all:
        type: boolean
        required: false
        default: false
        description: Remake all images instead of only the missing ones.

env:
  DEPLOY-ALL: ${{ ( github.event_name == 'workflow_run' && github.event.workflow == 'Deploy Image -- Latest' ) || ( github.event_name == 'workflow_dispatch' && github.event.inputs.deploy-all == 'true' ) }}

jobs:
  echo-caller:
    runs-on: ubuntu-latest
    steps:
    - name: Echo run by workflow_run
      if: ${{ github.event_name == 'workflow_run' && github.event.workflow == 'Deploy .tar.gz files'}}
      run: |
        echo "The workflow was called by \"Deploy .tar.gz files\" workflow running."
    - name: Echo run by workflow_run
      if: ${{ github.event_name == 'workflow_run' && github.event.workflow == 'Deploy Image -- Latest'}}
      run: |
        echo "The workflow was called by \"Deploy Image -- Latest\" workflow running."
    - name: Echo run by dispatch
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy-all == 'true'}}
      run: |
        echo "The workflow was called manually, requesting to deploy all."
    - name: Echo run by dispatch
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy-all == 'false'}}
      run: |
        echo "The workflow was called manually, only deploying a few."
    - name: Version 1
      if: $DEPLOY-ALL == 'true'
      run: |
        echo "Version 1 worked."
    # - name: Version 2
    #   if: ${{ $DEPLOY-ALL == 'true' }}
    #   run: |
    #     echo "Version 2 worked."