name: Deploy .tar.gz files

on: workflow-dispatch
  # push:
  #   branches:
  #   - main
  #   paths:
  #   - 'Dockerfile'
  #   - '*/Dockerfile'
  #   - '.github/workflows/deploy-image.yml'

jobs:
  list-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - id: set-matrix
      run: echo "::set-output name=matrix::$(cat versions.txt | jq -R -s -c 'split("\n")[:-1]')"

  process-version:
    needs: list-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-versions.outputs.matrix) }}
    with:
      version: ${{ matrix.manifest }}
    steps:
    - uses: actions/checkout@v2   
    - run: |
      echo ${version}
