name: Deploy Image -- Latest

on:
  push:
    branches:
    - main
    paths:
    - 'Dockerfile'
    - '*/Dockerfile'
    - '.github/workflows/deploy-image.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the Docker base image
      run: docker build bossdocker-base --file bossdocker-base/Dockerfile --tag bossdocker-base:latest
    - name: Build the main Docker image
      run: docker build bossdocker --file bossdocker/Dockerfile --tag bossdocker:latest
    - name: Build the Docker installer image
      run: docker build bossdocker-installboss --file bossdocker-installboss/Dockerfile --tag bossdocker-installboss:latest
    - name: Build the Docker install-and-cache image
      run: docker build bossdocker-installboss-cache --file bossdocker-installboss-cache/Dockerfile --tag bossdocker-installboss-cache:latest
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.azurecr_url }}
        username: ${{ secrets.azurecr_login }}
        password: ${{ secrets.azurecr_pass }}
    - name: Upload Docker Image
      run: |
        docker tag bossdocker:latest ${{ secrets.azurecr_url }}/boss:latest
        docker push ${{ secrets.azurecr_url }}/boss:latest
        docker tag bossdocker-base:latest ${{ secrets.azurecr_url }}/bossdocker-base:latest
        docker push ${{ secrets.azurecr_url }}/bossdocker-base:latest
        docker tag bossdocker-installboss:latest ${{ secrets.azurecr_url }}/bossdocker-installboss:latest
        docker push ${{ secrets.azurecr_url }}/bossdocker-installboss:latest
        docker tag bossdocker-installboss-cache:latest ${{ secrets.azurecr_url }}/bossdocker-installboss-cache:latest
        docker push ${{ secrets.azurecr_url }}/bossdocker-installboss-cache:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.dockerhub_login }}
        password: ${{ secrets.dockerhub_pass }}
    - name: Upload Docker Image
      run: |
        docker tag bossdocker:latest jreher/boss:latest
        docker push jreher/boss:latest
        docker tag bossdocker-base:latest jreher/boss:utils-base
        docker push jreher/boss:utils-base
        docker tag bossdocker-installboss:latest jreher/boss:utils-install
        docker push jreher/boss:utils-install
        docker tag bossdocker-installboss-cache:latest jreher/boss:utils-cache
        docker push jreher/boss:utils-cache
