name: Deploy to Dockerhub

on:
  push:
    branches:
    - main
    paths:
    - Dockerfile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bossdocker:latest
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.azurecr_url }}
        username: ${{ secrets.azurecr_login }}
        password: ${{ secrets.azurecr_pass }}
    - name: Upload Docker Image
      run: |
        docker tag bossdocker:latest ${{ secrets.azurecr_url }}/boss:latest
        docker push ${{ secrets.azurecr_url }}/boss:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.dockerhub_login }}
        password: ${{ secrets.dockerhub_pass }}
    - name: Upload Docker Image
      run: |
        docker tag bossdocker:latest jreher/boss:latest
        docker push jreher/boss:latest
