name: Deploy Image -- Latest

on:
  push:
    branches:
    - main
    paths:
    - 'Dockerfile'
    - '*/Dockerfile'
    - '.github/workflows/deploy-image.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker CR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.dockerhub_login }}
        password: ${{ secrets.dockerhub_pass }}
    - name: Build and push base
      uses: docker/build-push-action@v2
      with:
        context: bossdocker-base
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          jreher/boss:utils-base
          ghcr.io/${{ github.repository_owner }}/boss:utils-base
    - name: Build and push main
      uses: docker/build-push-action@v2
      with:
        context: bossdocker
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          jreher/boss:latest
          ghcr.io/${{ github.repository_owner }}/boss:latest
    - name: Build and push install
      uses: docker/build-push-action@v2
      with:
        context: bossdocker-installboss
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          jreher/boss:utils-install
          ghcr.io/${{ github.repository_owner }}/boss:utils-install
    - name: Build and push installcache
      uses: docker/build-push-action@v2
      with:
        context: bossdocker-installboss-cache
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          jreher/boss:utils-cache
          ghcr.io/${{ github.repository_owner }}/boss:utils-cache
