name: Deploy .tar.gz files

on: push
  # push:
  #   branches:
  #   - main
  #   paths:
  #   - 'Dockerfile'
  #   - '*/Dockerfile'
  #   - '.github/workflows/deploy-image.yml'

jobs:
  list-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Convert version list to Matrix
      id: set-matrix
      run: echo "::set-output name=matrix::$(cat versions.txt | jq -R -s -c 'split("\n")[:-1]')"

  process-version:
    needs: list-versions
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.hash-outputs.outputs.hash }}
    strategy:
      matrix:
        bossversion: ${{ fromJson(needs.list-versions.outputs.matrix) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Make Dummies
      run: |
        mkdir -p ~/out
        cd ~/out
        echo "If this is the problem I'm mad." >> cmthome-${{ matrix.bossversion }}.tar.gz
        echo "If this is the problem I'm mad." >> cvmfs-cache-${{ matrix.bossversion }}.tar.gz
        echo "If this is the problem I'm mad." >> TestRelease-${{ matrix.bossversion }}.tar.gz
        pwd
        ls -l
    - id: hash-outputs
      run: |
        echo "Test: ${{ hashFiles('/home/runner/**') }}"
        echo "::set-output name=matrix::${{ hashFiles('/home/runner/**') }}" 
    - name: Cache tar files
      uses: actions/cache@v3
      with:
        path: ~/out
        key: tarcache-${{ matrix.bossversion }}-${{ hashFiles('/home/runner/**') }}

  deploy-version:
    needs: [process-version, list-versions]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bossversion: ${{ fromJson(needs.list-versions.outputs.matrix) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Restore Cached tar files
      uses: actions/cache@v3
      with:
        path: ~/out
        key: tarcache-${{ matrix.bossversion }}-${{ needs.process-version.outputs.hash }}
        restore-keys: tarcache-${{ matrix.bossversion }}
    - name: Upload cmthome files
      uses: nogsantos/scp-deploy@master
      with:
        src: /home/runner/out/cmthome-${{ matrix.bossversion }}.tar.gz
        host: ${{ secrets.SSH_HOST }}
        remote: ${{ secrets.SSH_DIR }}/cmthome/
        port: ${{ secrets.SSH_PORT }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
    - name: Upload TestRelease files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "/home/runner/out/testrelease-${{ matrix.bossversion }}.tar.gz"
        target: ${{ secrets.SSH_DIR }}/testrelease/
    - name: Upload cvmfs-cache files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "/home/runner/out/cvmfs-cache-${{ matrix.bossversion }}.tar.gz"
        target: ${{ secrets.SSH_DIR }}/cache/
    