name: Deploy Image -- Latest

on:
  push:
    branches:
    - main
    paths:
    - 'Dockerfile'
    - '*/Dockerfile'
    - '.github/workflows/deploy-image.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.dockerhub_login }}
        password: ${{ secrets.dockerhub_pass }}

    - name: Build and push base
      uses: docker/build-push-action@v2
      with:
        context: bossdocker-base
        push: true
        tags: |
          jreher/boss:utils-base
    - name: Build and push main
      uses: docker/build-push-action@v2
      with:
        context: bossdocker
        push: true
        tags: |
          jreher/boss:latest
    - name: Build and push install
      uses: docker/build-push-action@v2
      with:
        context: bossdocker-installboss
        push: true
        tags: |
          jreher/boss:utils-install
    - name: Build and push installcache
      uses: docker/build-push-action@v2
      with:
        context: bossdocker-installboss-cache
        push: true
        tags: |
          jreher/boss:utils-cache
