name: Deploy all versions

on:
  workflow_run:
    workflows: [Deploy .tar.gz files, Deploy Image -- Latest]
    types:
      - completed
  workflow_dispatch:
    inputs:
      deploy-all:
        type: boolean
        required: false
        default: false
        description: Remake all images instead of only the missing ones.

jobs:
  echo-caller:
    runs-on: ubuntu-latest
    steps:
    - name: Echo run by workflow_run
      if: ${{ github.event_name == 'workflow_run' }}
      run: |
        echo "The workflow was called by another workflow running!"
        echo "Action: ${{ github.event.action }}"
    - name: Echo run by dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "The workflow was called manually!"
        echo "Input: ${{ github.event.inputs.deploy-all }}"
    - name: Echo debug stuff
      run: |
        echo "Action: ${{ github.event.action }}"