name: Deploy Image -- Latest

on:
  push:
    branches:
    - main
    paths:
    - 'Dockerfile'
    - '*/Dockerfile'
    - '.github/workflows/deploy-image.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push base
      uses: docker/build-push-action@v2
      with:
        context: bossdocker-base
        push: false
        load: true
        tags: boss:utils-base
    - name: Re-Tag Base
      run: |
        docker tag boss:utils-base bossdocker-base:latest
        docker image ls

    - name: Build and push main
      uses: docker/build-push-action@v2
      with:
        context: bossdocker
        push: false
        load: true
        tags: boss:latest

    - name: Build and push install
      uses: docker/build-push-action@v2
      with:
        context: bossdocker-installboss
        push: false
        load: true
        tags: boss:utils-install

    - name: Re-Tag Install
      run: |
        docker tag boss:utils-install bossdocker-installdocker:latest

    - name: Cache Docker layers - Installcache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-installcache
        key: ${{ runner.os }}-buildx-installcache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-installcache
    - name: Build and push installcache
      uses: docker/build-push-action@v2
      with:
        context: bossdocker-installboss-cache
        push: false
        load: true
        tags: boss:utils-cache
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.dockerhub_login }}
        password: ${{ secrets.dockerhub_pass }}
    - name: Upload Docker Image
      run: |
        docker tag bossdocker:latest jreher/boss:latest
        docker push jreher/boss:latest
        docker tag bossdocker-base:latest jreher/boss:utils-base
        docker push jreher/boss:utils-base
        docker tag bossdocker-installboss:latest jreher/boss:utils-install
        docker push jreher/boss:utils-install
        docker tag bossdocker-installboss-cache:latest jreher/boss:utils-cache
        docker push jreher/boss:utils-cache


    # - name: Login to Azure Container Registry
    #   uses: azure/docker-login@v1
    #   with:
    #     login-server: ${{ secrets.azurecr_url }}
    #     username: ${{ secrets.azurecr_login }}
    #     password: ${{ secrets.azurecr_pass }}
    # - name: Upload Docker Image
    #   run: |
    #     docker tag bossdocker:latest ${{ secrets.azurecr_url }}/boss:latest
    #     docker push ${{ secrets.azurecr_url }}/boss:latest
    #     docker tag bossdocker-base:latest ${{ secrets.azurecr_url }}/bossdocker-base:latest
    #     docker push ${{ secrets.azurecr_url }}/bossdocker-base:latest
    #     docker tag bossdocker-installboss:latest ${{ secrets.azurecr_url }}/bossdocker-installboss:latest
    #     docker push ${{ secrets.azurecr_url }}/bossdocker-installboss:latest
    #     docker tag bossdocker-installboss-cache:latest ${{ secrets.azurecr_url }}/bossdocker-installboss-cache:latest
    #     docker push ${{ secrets.azurecr_url }}/bossdocker-installboss-cache:latest
