name: Deploy all versions

on:
  workflow_run:
    workflows: |
      Deploy .tar.gz files
      Deploy Image -- Latest
    types:
      - completed
  workflow_dispatch:
    inputs:
      deploy-all:
        type: boolean
        required: false
        default: false
        description: Remake all images instead of only the missing ones.

env:
  DEPLOY_ALL: ${{ ( github.event_name == 'workflow_run' && github.event.workflow == 'Deploy Image -- Latest' ) || ( github.event_name == 'workflow_dispatch' && github.event.inputs.deploy-all == 'true' ) }}

jobs:
  echo-caller:
    runs-on: ubuntu-latest
    steps:
    - name: Version 1
      if: ${{ env.DEPLOY_ALL == 'true' }}
      run: |
        echo "Version 1 worked."
  
  list-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@3
    - name: List versions to upload
      if: ${{ env.DEPLOY_ALL == 'false' }}
      run: |
        echo "This will go through versions and list the missing ones in a new file 'versions_process.txt'"
        while IFS="" read -r p || [ -n "$p" ]
        do
          if $p != '7.0.5'; then
            echo "Hit! $p"
            $p >> versions_process.txt
          fi
        done <versions.txt
    - name: 
      if: ${{ env.DEPLOY_ALL == 'true' }}
      run: |
        cp versions.txt versions_process.txt
    - name: Turn new list into output for matrix
      id: set-matrix
      run: |
        echo "This will take 'versions_processed.txt', created by one of the steps above, and turn it into an output that I can use to initiate a matrix job in the next step"
        echo "Reference processed:"
        cat versions_processed.txt
        echo "Reference raw:"
        cat versions.txt