name: Docker Image CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get today's Date
      id: datetime
      run: echo "::set-output name=datetime::$(date +%Y%m%d-%H%M%S)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bossdocker:latest
    - name: Upload the Docker image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "bossdocker:latest"
        retention_days: "2"
  
  test-boss:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: "bossdocker:latest"
    - name: Test boss.exe workflow
      uses: addnab/docker-run-action@v3
      with:
        image: bossdocker:latest
        options: --security-opt label=disable --workdir /root/workarea --privileged
        run: |
          source /root/mount.sh
          source /root/setup.sh
          cd /root/workarea/TestRelease/*/run
          boss.exe jobOptions_sim.txt
          boss.exe jobOptions_rec.txt
          boss.exe jobOptions_ana_rhopi.txt
    
test-cmt:
  needs: build
  runs-on: ubuntu-latest
  
  steps:
  - name: Download image
    uses: ishworkh/docker-image-artifact-download@v1
    with:
      image: "bossdocker:latest"
  - name: Test cmt workflow
    uses: addnab/docker-run-action@v3
    with:
      image: bossdocker:latest
      options: --security-opt label=disable --workdir /root/workarea --privileged
      run: |
        source /root/mount.sh
        source /root/setup.sh
        cd /root/workarea/TestRelease/*/cmt
        cmt clean
        cmt config
        cmt make

  clean:
    needs: [test-boss, test-cmt]
    runs-on: ubuntu-latest
    steps:
    - name: Remove Docker Artifact
      uses: geekyeggo/delete-artifact@v1
      with:
        name: action_image_artifact_bossdocker_latest
