name: Final new line
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  add-newlines:
    name: Add Newlines
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Linelint
      uses: fernandrone/linelint@0.0.4
      id: linelint


      