name: Final new line
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  add-newlines:
    name: Add Newlines
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Linelint
      uses: actions/linelint@master
      id: linelint


      