name: Docker Image CI

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bossdocker:latest
  
  test-boss:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Rebuild the image
      run: docker build . --file Dockerfile --tag bossdocker:latest
    - name: Test boss.exe workflow
      uses: addnab/docker-run-action@v3
      with:
        image: bossdocker:latest
        options: --security-opt label=disable --workdir /root/workarea --privileged
        run: |
          source /root/mount.sh
          source /root/setup.sh
          cd /root/workarea/TestRelease/*/run
          boss.exe jobOptions_sim.txt
          boss.exe jobOptions_rec.txt
          boss.exe jobOptions_ana_rhopi.txt
    
  test-cmt:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bossdocker:latest
    - name: Test cmt workflow
      uses: addnab/docker-run-action@v3
      with:
        image: bossdocker:latest
        options: --security-opt label=disable --workdir /root/workarea --privileged
        run: |
          source /root/mount.sh
          source /root/setup.sh
          cd /root/workarea/TestRelease/*/cmt
          cmt clean
          cmt config
          cmt make
