name: Lint Only

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'Dockerfile'
    - '*/Dockerfile'
    - '.github/workflows/test-image.yml'
    - 'bossdocker-base/external/*'
    - 'inputs/*'
  push:
    branches:
    - main
    paths-ignore:
    - 'Dockerfile'
    - '*/Dockerfile'
    - '.github/workflows/test-image.yml'
    - 'bossdocker-base/external/*'
    - 'inputs/*'

jobs:
  lint-bossdocker-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'Dockerfile'

  lint-base-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'bossdocker-base/Dockerfile'

  lint-install-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'bossdocker-installboss/Dockerfile'

  lint-cache-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'bossdocker-installboss-cache/Dockerfile'
  
  lint-shellscripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run ShellCheck for Docker
      uses: azohra/shell-linter@latest
      with:
        path: "scripts/*.sh"
      env:
        SHELLCHECK_OPTS: -e SC2086
    - name: Run ShellCheck for Podman
      uses: azohra/shell-linter@latest
      with:
        path: "scripts-podman/*.sh"
      env:
        SHELLCHECK_OPTS: -e SC2086
    - name: Run ShellCheck for includes
      uses: azohra/shell-linter@latest
      with:
        path: "inputs/*"
      env:
        SHELLCHECK_OPTS: -e SC2086
  
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: No build or test required
      run: echo No build or test required
    