name: Lint, build and test

on:
  pull_request:
    branches:
    - main
    paths:
    - 'Dockerfile'
    - 'bossdocker/Dockerfile'
    - 'bossdocker-base/Dockerfile'
    - 'bossdocker-installboss/Dockerfile'
    - 'bossdocker-installboss-cache/Dockerfile'
  push:
    branches:
    - main
    paths:
    - "Dockerfile"
    - 'bossdocker/Dockerfile'
    - 'bossdocker-base/Dockerfile'
    - 'bossdocker-installboss/Dockerfile'
    - 'bossdocker-installboss-cache/Dockerfile'

jobs:
  lint-bossdocker-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'bossdocker/Dockerfile'

  lint-base-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'bossdocker-base/Dockerfile'

  lint-install-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'bossdocker-installboss/Dockerfile'

  lint-cache-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'bossdocker-installboss-cache/Dockerfile'
  
  lint-shellscripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: azohra/shell-linter@latest
      with:
        path: "scripts/*.sh"
  
  build-and-test:
    needs: [lint-dockerfile, lint-shellscripts]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the Docker base image
      run: docker build bossdocker-base --file Dockerfile --tag bossdocker-base:latest
    - name: Build the Docker base image
      run: docker build bossdocker-base --file Dockerfile --tag bossdocker:latest
    - name: Build the Docker base image
      run: docker build bossdocker-base --file Dockerfile --tag bossdocker-installboss:latest
    - name: Build the Docker base image
      run: docker build bossdocker-base --file Dockerfile --tag bossdocker-installboss-cache:latest
    - name: Test sim, reco and ana with boss.exe 
      uses: addnab/docker-run-action@v3
      with:
        image: bossdocker:latest
        options: --security-opt label=disable --workdir /root/workarea --privileged
        run: |
          source /root/mount.sh
          source /root/setup.sh
          cd /root/workarea/TestRelease/*/run
          boss.exe jobOptions_sim.txt
          boss.exe jobOptions_rec.txt
          boss.exe jobOptions_ana_rhopi.txt
    - name: Test compiling with cmt
      uses: addnab/docker-run-action@v3
      with:
        image: bossdocker:latest
        options: --security-opt label=disable --workdir /root/workarea --privileged
        run: |
          source /root/mount.sh
          source /root/setup.sh
          cd /root/workarea/TestRelease/*/cmt
          cmt clean
          cmt config
          cmt make